In [8]:
import numpy as np

## Datatype and Atributes

In [9]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [10]:
a2=np.array([[1,2,3],[3.5,4.5,6.7]])
a2

array([[1. , 2. , 3. ],
       [3.5, 4.5, 6.7]])

In [11]:
a1.shape

(3,)

In [12]:
import pandas as pd

In [13]:
df=pd.DataFrame(a2)

In [14]:
df

0    1    2
0  1.0  2.0  3.0
1  3.5  4.5  6.7

## Creating arrays

In [17]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array=np.arange(0,10,2)

In [21]:
range_array

array([0, 2, 4, 6, 8])

In [31]:
np.random.seed(seed=0)
random_array=np.random.randint(0,10, size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

## Viewing Array and Matrices


In [33]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a2[0]


array([1., 2., 3.])

In [41]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a3[0]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a3.shape

(2, 3, 3)

In [43]:
a3.size

18

In [44]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [47]:
a4[:,:,:4:5]

array([[[[6, 7, 7, 8, 1]],

        [[3, 3, 7, 0, 1]],

        [[8, 4, 1, 4, 9]]],


       [[[4, 6, 4, 4, 3]],

        [[0, 1, 2, 4, 2]],

        [[2, 3, 4, 1, 2]]]])

## 4.Manipulating Arrays

### Arithmetic

In [48]:
a1

array([1, 2, 3])

In [49]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [51]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [52]:
a1*ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [53]:
np.sum(a1)

6

In [54]:
massive_array=np.random.random(100000)
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

## Reshaping and transposing

In [55]:
a2


array([[1. , 2. , 3. ],
       [3.5, 4.5, 6.7]])

In [56]:
a2.shape

(2, 3)

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a3.shape

(2, 3, 3)

In [59]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[3.5],
        [4.5],
        [6.7]]])

In [60]:
a2_reshape=a2.reshape(2,3,1)

In [61]:
a2_reshape

array([[[1. ],
        [2. ],
        [3. ]],

       [[3.5],
        [4.5],
        [6.7]]])

In [62]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 35. ,  38.5,  42. ],
        [ 58.5,  63. ,  67.5],
        [107.2, 113.9, 120.6]]])

In [63]:
a2.T

array([[1. , 3.5],
       [2. , 4.5],
       [3. , 6.7]])

In [64]:
a2.T.shape

(3, 2)

## Dot product

In [67]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1
mat2


array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [68]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [69]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [75]:
mat1.T.shape
mat3=mat1.T

In [76]:
np.dot(mat3,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [77]:
mat3.shape

(3, 5)

In [80]:
np.random.seed(0)
sales_amounts=np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [82]:
##Create Week Sales Data Frame
weekly_sales=pd.DataFrame(sales_amounts,
                          index=["Mon","Tue","Wed","Thu","Fri"],
                          columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales



Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [86]:
##create price array
prices=np.array([10,8,12])

prices
prices.shape


(3,)

In [87]:
## create butter Dataframe Prices
butter_prices=pd.DataFrame(prices.reshape(1,3),
                          index=["Price"],
                          columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [91]:
total_sales=butter_prices.dot(sales_amounts.T)
total_sales

0    1    2    3    4
Price  240  138  458  232  142

In [93]:
#create daily sales
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [94]:
daily_sales=butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thu  Fri
Price  240  138  458  232  142

In [97]:

weekly_sales["Total Sales"]=daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Sales
Mon             12             15              0          240
Tue              3              3              7          138
Wed              9             19             18          458
Thu              4              6             12          232
Fri              1              6              7          142

## comparisonOpertors

In [98]:
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [99]:
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]])

In [102]:
np.argmax(random_array,axis=0)

array([1, 2, 2, 2, 0])

In [103]:
np.argmax(random_array,axis=1)

array([4, 0, 2])

<img src="panda.png"/>

In [105]:
##Tutn an image into an numpy array
from matplotlib.image import imread
panda=imread("panda.png")

In [106]:
panda.size

24465000

In [107]:
panda.shape

(2330, 3500, 3)

In [109]:
panda.ndim

3