# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [4]:
# Create a 1-dimensional NumPy array using np.array()
one_d_array=np.array([1,2,3])


# Create a 2-dimensional NumPy array using np.array()
two_d_array=np.array([[1,2,3],[4,5,6]])


# Create a 3-dimensional Numpy array using np.array()
three_d_array=np.array([[1,2,3],[4,5,6],[7,8,9]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d_array.ndim


1

In [7]:
one_d_array.dtype


dtype('int64')

In [8]:

one_d_array.size


3

In [9]:

type(one_d_array)

numpy.ndarray

In [10]:
# Attributes of 2-dimensional array
two_d_array.ndim




2

In [11]:
two_d_array.dtype

dtype('int64')

In [12]:
two_d_array.size

6

In [13]:
type(two_d_array)

numpy.ndarray

In [14]:
# Attributes of 3-dimensional array
three_d_array.ndim

2

In [15]:
three_d_array.size

9

In [16]:
three_d_array.dtype

dtype('int64')

In [17]:
type(three_d_array)

numpy.ndarray

In [18]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
array_df=pd.DataFrame(three_d_array)
array_df


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [20]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
range_num=np.arange(0,100,3)
range_num


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_numbers=np.random.randint(10,size=(7,2))
random_numbers


array([[7, 3],
       [3, 4],
       [5, 5],
       [7, 8],
       [9, 6],
       [6, 4],
       [3, 8]])

In [29]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_numbers2=np.random.random((3,5))
random_numbers2

array([[0.41931686, 0.4139822 , 0.36425644, 0.45009189, 0.53415234],
       [0.57222479, 0.98446555, 0.84539208, 0.97525151, 0.84515608],
       [0.97797706, 0.55806063, 0.0094118 , 0.98305344, 0.84037969]])

In [31]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_numbers3=np.random.randint(0,10,size=(4,6))
random_numbers3


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [36]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers4=np.random.randint(1,10,size=(3,7))
random_numbers4

# Find the unique numbers in the array you just created
#np.unique(random_numbers4)


array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [37]:
# Find the 0'th index of the latest array you created
random_numbers4[0]

array([2, 5, 8, 9, 9, 1, 9])

In [38]:
# Get the first 2 rows of latest array you created
random_numbers4[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [39]:
# Get the first 2 values of the first 2 rows of the latest array
random_numbers4[:2,:2]

array([[2, 5],
       [7, 9]])

In [40]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_numbers5=np.random.randint(0,10,size=(3,5))
ones_array=np.ones((3,5))

In [41]:
random_numbers5


array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [42]:
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Add the two arrays together
np.add(random_numbers5,ones_array)

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [44]:
# Create another array of ones of shape (5, 3)
ones_array2=np.ones((5,3))

In [46]:
# Try add the array of ones and the other most recent array together
np.add(ones_array,ones_array2.T)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [47]:
# Create another array of ones of shape (3, 5)
ones_array3=np.ones((3,5))

In [49]:
# Subtract the new array of ones from the other most recent array
np.subtract(ones_array2,ones_array3.T)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# Multiply the ones array with the latest array
np.multiply(ones_array3,random_numbers5)

array([[9., 8., 6., 8., 7.],
       [1., 0., 6., 6., 7.],
       [4., 2., 7., 5., 2.]])

In [51]:
# Take the latest array to the power of 2 using '**'
random_numbers5**2

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [52]:
# Do the same thing with np.square()
np.square(random_numbers5)

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [53]:
# Find the mean of the latest array using np.mean()
np.mean(random_numbers5)

5.2

In [54]:
# Find the maximum of the latest array using np.max()
np.max(random_numbers5)

9

In [55]:
# Find the minimum of the latest array using np.min()
np.min(random_numbers5)

0

In [56]:
# Find the standard deviation of the latest array
np.std(random_numbers5)

2.6882460204874605

In [57]:
# Find the variance of the latest array
np.var(random_numbers5)

7.2266666666666675

In [58]:
# Reshape the latest array to (3, 5, 1)
random_numbers5.reshape(3,5,1)

array([[[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]],

       [[4],
        [2],
        [7],
        [5],
        [2]]])

In [59]:
# Transpose the latest array
random_numbers5.T

array([[9, 1, 4],
       [8, 0, 2],
       [6, 6, 7],
       [8, 6, 5],
       [7, 7, 2]])

What does the transpose do?

In [60]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_numbers6=np.random.randint(10,size=(3,3))
random_numbers7=np.random.randint(10,size=(3,2))

In [61]:
random_numbers6

array([[0, 2, 4],
       [2, 0, 4],
       [9, 6, 6]])

In [62]:
random_numbers7

array([[8, 9],
       [9, 2],
       [6, 0]])

In [64]:
# Perform a dot product on the two newest arrays you created
random_numbers6.dot(random_numbers7)

array([[ 42,   4],
       [ 40,  18],
       [162,  93]])

In [65]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_numbers8=np.random.randint(10,size=(4,3))
random_numbers9=np.random.randint(10,size=(4,3))

In [66]:
# Perform a dot product on the two newest arrays you created
random_numbers8.dot(random_numbers9.T)

array([[ 39,  77,  18,  60],
       [ 63, 114,  36, 105],
       [ 49, 106,  36,  79],
       [ 73, 127,   6, 104]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [68]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_numbers10=np.random.randint(10,size=(4,3))
random_numbers11=np.random.randint(10,size=(4,3))

In [69]:
# Compare the two arrays with '>'
random_numbers10>random_numbers11

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [70]:
# Compare the two arrays with '>='
random_numbers10>=random_numbers11

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [71]:
# Find which elements of the first array are greater than 7
random_numbers10>7

array([[ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [72]:
# Which parts of each array are equal? (try using '==')
random_numbers10==random_numbers11

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [73]:
# Sort one of the arrays you just created in ascending order
np.sort(random_numbers10)

array([[2, 6, 8],
       [5, 7, 8],
       [0, 2, 4],
       [5, 7, 9]])

In [74]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_numbers10)

array([[1, 2, 0],
       [0, 1, 2],
       [1, 2, 0],
       [2, 1, 0]])

In [78]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_numbers10)

array([0, 2, 0, 0])

In [79]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_numbers10)

array([1, 0, 1, 2])

In [80]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_numbers10,axis=1)

array([0, 2, 0, 0])

In [81]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_numbers10,axis=0)

array([2, 2, 2])

In [87]:
# Create an array of normally distributed random numbers
random_numbers11=np.random.randn(3,5)
random_numbers11


array([[-0.08008734, -0.24138013,  1.43351549,  1.06579371, -2.49875914],
       [ 1.48032856,  2.15872852,  1.23177838, -0.21432448, -0.68919421],
       [ 0.72783311, -0.61906936,  0.35615983, -0.02188087,  1.21805044]])

In [89]:
# Create an array with 10 evenly spaced numbers between 1 and 100
random_numbers12=np.linspace(1,100,10)
random_numbers12

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.